import { describe, expect, it } from "vitest";
import { SEED_WORKSPACE } from "../data/seed";
import type { CarryoverWorkspaceV2 } from "../domain";
import { acknowledgeHandoff, approveAction, assignAction, can, createObservation, isWorkspace, loadWorkspace, migrateV1, overdue, prepareHandoff, returnAction, submitActionEvidence, tourStep, unresolved, type WorkspaceRepository } from "./workspace";

const clone = () => structuredClone(SEED_WORKSPACE);
class MemoryRepository implements WorkspaceRepository {
  current: unknown = null; legacy: unknown = null;
  load() { return this.current; }
  loadLegacy() { return this.legacy; }
  save(workspace: CarryoverWorkspaceV2) { this.current = structuredClone(workspace); }
  reset() { this.current = null; this.legacy = null; }
}

describe("workspace V2", () => {
  it("recognizes the beverage-packaging seed", () => { expect(isWorkspace(SEED_WORKSPACE)).toBe(true); expect(JSON.stringify(SEED_WORKSPACE)).not.toMatch(/winder|resin|composite/i); });
  it("restores the seed after corrupted persistence", () => { const repository = new MemoryRepository(); repository.current = { version: 2, issues: "broken" }; const result = loadWorkspace(repository); expect(result.recovered).toBe(true); expect(result.workspace.issues).toHaveLength(5); });
  it("migrates a structurally valid V1 record to the safe fictional V2 seed", () => { const migrated = migrateV1({ version: 1, issues: [], handoffs: [], actions: [] }); expect(migrated?.version).toBe(2); expect(migrated?.plant).toBe("Northshore Beverage Packaging"); });
  it("loads and marks a legacy migration", () => { const repository = new MemoryRepository(); repository.legacy = { version: 1, issues: [], handoffs: [], actions: [] }; const result = loadWorkspace(repository); expect(result.migrated).toBe(true); expect((repository.current as CarryoverWorkspaceV2).version).toBe(2); });
  it("keeps resolved conditions out of the active record", () => expect(unresolved(SEED_WORKSPACE.issues)).toHaveLength(4));
  it("finds deterministic overdue conditions", () => expect(overdue(SEED_WORKSPACE.issues, "2026-08-13T08:30").map((issue) => issue.id)).toEqual(["CO-202"]));
  it("enforces demonstration permissions", () => { expect(can("Operator", "observe")).toBe(true); expect(can("Operator", "prepare")).toBe(false); expect(can("Shift supervisor", "acknowledge")).toBe(true); expect(can("Plant manager", "approve")).toBe(true); });
  it("creates an observation with an immutable audit event", () => { const source = clone(); const next = createObservation({ ...source, role: "Operator" }, { title: "Bottle cap torque variation", equipment: "Filler 02", area: "Packaging hall", severity: "Moderate", owner: "Noah Williams", due: "2026-08-13T11:00", shift: "Day", observation: "Three bottles showed torque readings near the lower documented limit.", decision: "Repeat the sample before the next scheduled flavour changeover.", evidence: "Sample IDs C-1 through C-3 retained." }); expect(next.issues).toHaveLength(source.issues.length + 1); expect(source.issues).toHaveLength(5); expect(next.issues[0].audit[0].event).toBe("Observation recorded"); });
  it("validates and prepares a handoff", () => { const source = clone(); expect(() => prepareHandoff(source, { fromShift: "Day", toShift: "Evening", summary: "short", equipmentState: "short", workAttempted: "short", nextDecision: "short", issueIds: [] })).toThrow(); const next = prepareHandoff(source, { fromShift: "Day", toShift: "Evening", summary: "Labeler condition requires verification before normal speed resumes.", equipmentState: "Line remains available at reduced operating speed only.", workAttempted: "Guide rail was reset and spot checks were recorded by day shift.", nextDecision: "Evening shift must verify a complete run before normal release.", issueIds: ["CO-204"] }); expect(next.handoffs[0].status).toBe("Prepared"); expect(next.issues.find((issue) => issue.id === "CO-204")?.status).toBe("Carried over"); });
  it("acknowledges a transfer and changes responsibility", () => { const prepared = prepareHandoff(clone(), { fromShift: "Night", toShift: "Day", summary: "Labeler condition requires verification before normal speed resumes.", equipmentState: "Line remains available at reduced operating speed only.", workAttempted: "Guide rail was reset and spot checks were recorded by night shift.", nextDecision: "Day shift must verify a complete run before normal release.", issueIds: ["CO-201"] }); const id = prepared.handoffs[0].id; const next = acknowledgeHandoff(prepared, id, "Equipment state and isolated bottles were cross-checked at the line."); expect(next.handoffs.find((handoff) => handoff.id === id)?.status).toBe("Acknowledged"); expect(next.issues.find((issue) => issue.id === "CO-201")?.status).toBe("Acknowledged"); });
  it("assigns work and connects it to the source condition", () => { const next = assignAction(clone(), { issueId: "CO-201", title: "Verify Labeler 02 alignment", owner: "Elias Morgan", due: "2026-08-13T10:30", expectedProof: "Thirty consecutive bottles remain within the alignment tolerance.", approvalRequired: false }); const issue = next.issues.find((item) => item.id === "CO-201")!; expect(issue.status).toBe("In action"); expect(issue.linkedActionIds).toContain(next.actions[0].id); });
  it("requires meaningful resolution evidence", () => expect(() => submitActionEvidence(clone(), "AC-62", "short")).toThrow());
  it("routes approval-required proof to the manager", () => { const source = { ...clone(), role: "Operator" as const }; const waiting = submitActionEvidence(source, "AC-62", "Sensor alignment verified during a complete twenty-minute observed run."); expect(waiting.actions.find((item) => item.id === "AC-62")?.state).toBe("Evidence submitted"); });
  it("prevents a supervisor from approving manager-required work", () => expect(() => approveAction(clone(), "AC-61", "Quality hold can be released.")).toThrow());
  it("lets a manager return insufficient proof", () => { const next = returnAction({ ...clone(), role: "Plant manager" }, "AC-61", "Add the signed quality disposition."); expect(next.actions.find((item) => item.id === "AC-61")?.state).toBe("Open"); });
  it("closes the source condition only when all linked actions close", () => { let current = prepareHandoff(clone(), { fromShift: "Night", toShift: "Day", summary: "Labeler condition requires verification before normal speed resumes.", equipmentState: "Line remains available at reduced operating speed only.", workAttempted: "Guide rail was reset and spot checks were recorded by night shift.", nextDecision: "Day shift must verify a complete run before normal release.", issueIds: ["CO-201"] }); current = acknowledgeHandoff(current, current.handoffs[0].id, "Equipment state and isolated bottles were cross-checked at the line."); current = assignAction(current, { issueId: "CO-201", title: "Verify Labeler 02 alignment", owner: "Elias Morgan", due: "2026-08-13T10:30", expectedProof: "Thirty consecutive bottles remain within the alignment tolerance.", approvalRequired: false }); const actionId = current.actions[0].id; current = submitActionEvidence(current, actionId, "Thirty consecutive bottles remained within documented alignment tolerance."); current = approveAction(current, actionId, "Normal operating speed may resume."); expect(current.issues.find((item) => item.id === "CO-201")?.status).toBe("Resolved"); expect(tourStep(current)).toBe(6); });
});
