import { useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { useWorkspace } from "../WorkspaceContext";
import { acknowledgeHandoff, can } from "../lib/workspace";

export default function HandoffDetail() {
  const { id } = useParams(); const location = useLocation(); const navigate = useNavigate();
  const { workspace, update } = useWorkspace(); const [note, setNote] = useState(""); const [error, setError] = useState("");
  const handoff = workspace.handoffs.find((item) => item.id === id);
  if (!handoff) return <div className="page empty"><h1>Handoff not found.</h1><Link to="/handoffs">Return to handoffs</Link></div>;
  const acknowledge = () => { try { update((current) => acknowledgeHandoff(current, handoff.id, note)); navigate(`/issues/${handoff.issueIds[0]}${location.search}`); } catch (reason) { setError((reason as Error).message); } };
  return <div className="page transfer-page"><div className="detail-top"><Link to="/handoffs">← Handoff ledger</Link><span>{handoff.id} · {handoff.status}</span></div><header><p className="eyebrow">Responsibility transfer · {handoff.fromShift} → {handoff.toShift}</p><h1>Cross-check before the work changes hands.</h1></header><div className="transfer-ledger"><section><div className="ledger-label"><span>01</span><strong>Outgoing preparation</strong></div><h2>{handoff.summary}</h2><dl><div><dt>Equipment state</dt><dd>{handoff.equipmentState}</dd></div><div><dt>Work attempted</dt><dd>{handoff.workAttempted}</dd></div><div><dt>Next decision</dt><dd>{handoff.nextDecision}</dd></div></dl><div className="linked-records">{handoff.issueIds.map((issueId) => { const issue = workspace.issues.find((item) => item.id === issueId)!; return <Link to={`/issues/${issue.id}`} key={issue.id}><span>{issue.id}</span><strong>{issue.title}</strong><small>{issue.equipment} · {issue.severity}</small></Link>; })}</div></section><section className="incoming-panel"><div className="ledger-label"><span>02</span><strong>Incoming cross-check</strong></div>{handoff.status === "Acknowledged" ? <div className="acceptance"><span>✓ Responsibility accepted</span><h2>{handoff.acknowledgedBy}</h2><p>{handoff.acknowledgementNote}</p><small>{handoff.acknowledgedAt?.replace("T", " · ")}</small></div> : <><h2>Confirm what you checked.</h2><p>Cross-check the equipment state, linked conditions, and next decision before accepting responsibility.</p><label>Incoming verification note<textarea rows={6} value={note} onChange={(event) => setNote(event.target.value)} placeholder="Record what was verified at the line and any clarification received."/><small>{note.length}/500 · minimum 20</small></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary" type="button" onClick={acknowledge} disabled={!can(workspace.role, "acknowledge")}>Acknowledge responsibility</button>{!can(workspace.role, "acknowledge") && <p className="permission-note">Shift supervisor or plant manager role required.</p>}</>}</section></div><section className="audit"><p className="eyebrow">Transfer history</p><h2>One record, both sides.</h2>{handoff.audit.slice().reverse().map((entry) => <article key={entry.id}><time>{entry.at.replace("T", " · ")}</time><div><strong>{entry.event}</strong><span>{entry.actor}</span>{entry.detail && <p>{entry.detail}</p>}</div></article>)}</section></div>;
}
