import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { useWorkspace } from "../WorkspaceContext";
import { can, prepareHandoff, unresolved } from "../lib/workspace";
import type { Shift } from "../domain";

const initial = { fromShift: "Day" as Shift, toShift: "Evening" as Shift, summary: "", equipmentState: "", workAttempted: "", nextDecision: "" };
export default function Handoffs() {
  const { workspace, update } = useWorkspace();
  const navigate = useNavigate();
  const location = useLocation();
  const [form, setForm] = useState(initial);
  const [selected, setSelected] = useState<string[]>([]);
  const [error, setError] = useState("");
  const submit = (event: React.FormEvent) => { event.preventDefault(); try { let created = ""; update((current) => { const next = prepareHandoff(current, { ...form, issueIds: selected }); created = next.handoffs[0].id; return next; }); navigate(`/handoffs/${created}${new URLSearchParams(location.search).has("tour") ? "?tour=handoff" : ""}`); } catch (reason) { setError((reason as Error).message); } };
  const loadGuidedRecord = () => { setForm({ fromShift: "Night", toShift: "Day", summary: "Labeler 02 can run only at reduced speed until a complete 30-bottle alignment check is recorded.", equipmentState: "Line available at 60% speed; four affected bottles remain isolated at the quality station.", workAttempted: "Guide rail was reset to the changeover reference mark and four spot checks were completed.", nextDecision: "Incoming shift must confirm whether alignment holds across 30 consecutive bottles." }); setSelected(["CO-201"]); };
  return <div className="page"><header className="page-head compact"><div><p className="eyebrow">Handoffs · Two-way transfer</p><h1>Prepare the record the next shift must trust.</h1><p>Outgoing context and incoming verification remain distinct, visible, and jointly accountable.</p></div></header>
    <div className="handoff-layout"><form className="composer" onSubmit={submit}><div className="form-head"><span>Outgoing preparation</span><strong>{form.fromShift} → {form.toShift}</strong>{new URLSearchParams(location.search).has("tour") && <button type="button" className="load-scenario" onClick={loadGuidedRecord}>Load guided record</button>}</div><div className="form-pair"><label>From shift<select value={form.fromShift} onChange={(event) => setForm({ ...form, fromShift: event.target.value as Shift })}><option>Night</option><option>Day</option><option>Evening</option></select></label><label>To shift<select value={form.toShift} onChange={(event) => setForm({ ...form, toShift: event.target.value as Shift })}><option>Night</option><option>Day</option><option>Evening</option></select></label></div>{([['summary','What must the incoming shift understand?'],['equipmentState','What state is the equipment in?'],['workAttempted','What has already been tried?'],['nextDecision','What decision must happen next?']] as const).map(([key,label]) => <label key={key}>{label}<textarea value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} rows={3} maxLength={500}/><small>{form[key].length}/500 · minimum 20</small></label>)}<fieldset><legend>Conditions that must carry over</legend>{unresolved(workspace.issues).map((issue) => <label className="check" key={issue.id}><input type="checkbox" checked={selected.includes(issue.id)} onChange={() => setSelected((current) => current.includes(issue.id) ? current.filter((id) => id !== issue.id) : [...current, issue.id])}/><span><strong>{issue.title}</strong><small>{issue.id} · {issue.equipment} · {issue.status}</small></span></label>)}</fieldset>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={!can(workspace.role, "prepare")}>Publish prepared handoff</button>{!can(workspace.role, "prepare") && <p className="permission-note">Shift supervisor or plant manager role required. Operators can record observations.</p>}</form>
      <section className="handoff-history"><p className="eyebrow">Transfer ledger</p><h2>Prepared and acknowledged</h2>{workspace.handoffs.map((handoff) => <Link className="handoff-record" to={`/handoffs/${handoff.id}`} key={handoff.id}><header><strong>{handoff.fromShift} → {handoff.toShift}</strong><span data-status={handoff.status}>{handoff.status}</span></header><p>{handoff.summary}</p><small>{handoff.issueIds.length} linked · prepared by {handoff.preparedBy}</small></Link>)}</section>
    </div>
  </div>;
}
