import { useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { PEOPLE } from "../data/seed";
import { useWorkspace } from "../WorkspaceContext";
import { assignAction, can } from "../lib/workspace";

export default function IssueDetail() {
  const { id } = useParams(); const location = useLocation(); const navigate = useNavigate(); const { workspace, update } = useWorkspace(); const issue = workspace.issues.find((item) => item.id === id);
  const [showAssign, setShowAssign] = useState(false); const [error, setError] = useState(""); const [form, setForm] = useState({ title: issue ? `Verify ${issue.equipment} operating condition` : "", owner: "Elias Morgan", due: "2026-08-13T10:30", expectedProof: "", approvalRequired: false });
  if (!issue) return <div className="page empty"><h1>Operating record not found.</h1><Link to="/issues">Return to issues</Link></div>;
  const submit = (event: React.FormEvent) => { event.preventDefault(); try { let actionId = ""; update((current) => { const next = assignAction(current, { ...form, issueId: issue.id }); actionId = next.actions[0].id; return next; }); navigate(`/actions/${actionId}${location.search}`); } catch (reason) { setError((reason as Error).message); } };
  const linkedHandoffs = workspace.handoffs.filter((handoff) => issue.linkedHandoffIds.includes(handoff.id)); const linkedActions = workspace.actions.filter((action) => issue.linkedActionIds.includes(action.id));
  return <div className="page detail"><div className="detail-top"><Link to="/issues">← Issue register</Link><span>{issue.id} · {issue.status}</span></div><header><p className="eyebrow">{issue.area} · {issue.shift} shift</p><h1>{issue.title}</h1><div className="detail-tags"><b data-severity={issue.severity}>{issue.severity}</b><span>{issue.equipment}</span><span>Owner · {issue.owner}</span><span>Due · {issue.due.replace("T", " ")}</span></div></header><div className="detail-grid"><section><p className="eyebrow">Observation</p><h2>What changed</h2><p>{issue.observation}</p></section><section className="decision"><p className="eyebrow">Continuity decision</p><h2>What the next shift must protect</h2><p>{issue.decision}</p></section><section><p className="eyebrow">Evidence</p><h2>What supports the record</h2><p>{issue.evidence || "No supporting evidence has been recorded yet."}</p>{issue.resolutionNote && <p><strong>Resolution:</strong> {issue.resolutionNote}</p>}</section></div>
    <section className="connections"><div className="section-title"><div><p className="eyebrow">Connected work</p><h2>Transfer, action, and proof.</h2></div>{issue.status !== "Resolved" && <button className="primary" type="button" onClick={() => setShowAssign(!showAssign)} disabled={!can(workspace.role, "assign")}>Assign action</button>}</div>{!can(workspace.role, "assign") && issue.status !== "Resolved" && <p className="permission-note">Shift supervisor or plant manager role required to assign work.</p>}{showAssign && <form className="inline-action-form" onSubmit={submit}><label>Action<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })}/></label><label>Owner<select value={form.owner} onChange={(event) => setForm({ ...form, owner: event.target.value })}>{PEOPLE.map((person) => <option key={person}>{person}</option>)}</select></label><label>Due<input type="datetime-local" value={form.due} onChange={(event) => setForm({ ...form, due: event.target.value })}/></label><label className="wide">Expected proof<textarea rows={3} value={form.expectedProof} onChange={(event) => setForm({ ...form, expectedProof: event.target.value })}/></label><label className="check"><input type="checkbox" checked={form.approvalRequired} onChange={(event) => setForm({ ...form, approvalRequired: event.target.checked })}/><span>Plant manager approval required</span></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary">Create action</button></form>}<div className="connection-grid"><article><span>Handoffs</span>{linkedHandoffs.length ? linkedHandoffs.map((handoff) => <Link to={`/handoffs/${handoff.id}`} key={handoff.id}><strong>{handoff.id} · {handoff.fromShift} → {handoff.toShift}</strong><small>{handoff.status}</small></Link>) : <p>No shift transfer linked.</p>}</article><article><span>Actions</span>{linkedActions.length ? linkedActions.map((action) => <Link to={`/actions/${action.id}`} key={action.id}><strong>{action.id} · {action.title}</strong><small>{action.state}</small></Link>) : <p>No corrective action assigned.</p>}</article></div></section>
    <section className="audit"><p className="eyebrow">Immutable audit history</p><h2>How the record changed</h2>{issue.audit.slice().reverse().map((entry) => <article key={entry.id}><time>{entry.at.replace("T", " · ")}</time><div><strong>{entry.event}</strong><span>{entry.actor}</span>{entry.detail && <p>{entry.detail}</p>}</div></article>)}</section></div>;
}
