import { useState } from "react";
import { Link } from "react-router-dom";
import { useWorkspace } from "../WorkspaceContext";
import { filterIssues } from "../lib/filters";
import type { Severity } from "../domain";

export default function Issues() {
  const { workspace } = useWorkspace(); const [query, setQuery] = useState(""); const [severity, setSeverity] = useState<"All" | Severity>("All"); const [state, setState] = useState<"All" | "Open" | "Resolved">("All");
  const result = filterIssues(workspace.issues, { query, severity, state });
  return <div className="page"><header className="page-head compact"><div><p className="eyebrow">Issues · Complete operating record</p><h1>Every condition remains legible.</h1><p>Search the complete record or capture a new observation before its context disappears.</p></div><Link className="primary" to="/issues/new">+ Record observation</Link></header><section className="filters" aria-label="Issue filters"><label>Search<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Issue, equipment, area, owner"/></label><label>Severity<select value={severity} onChange={(event) => setSeverity(event.target.value as typeof severity)}><option>All</option><option>Critical</option><option>High</option><option>Moderate</option><option>Low</option></select></label><label>State<select value={state} onChange={(event) => setState(event.target.value as typeof state)}><option>All</option><option>Open</option><option>Resolved</option></select></label><span>{result.length} records</span></section><div className="issue-table" role="table" aria-label="Plant conditions"><div className="issue-row issue-header" role="row"><span>ID</span><span>Condition</span><span>Equipment</span><span>Severity</span><span>Status</span><span>Owner</span></div>{result.map((issue) => <Link to={`/issues/${issue.id}`} className="issue-row" role="row" key={issue.id}><span>{issue.id}</span><strong>{issue.title}<small>{issue.area}</small></strong><span>{issue.equipment}</span><b data-severity={issue.severity}>{issue.severity}</b><span>{issue.status}</span><span>{issue.owner}</span></Link>)}</div>{result.length === 0 && <div className="empty"><strong>No conditions match these filters.</strong><p>Clear one or more filters to return to the operating record.</p></div>}</div>;
}
