import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { EQUIPMENT, PEOPLE } from "../data/seed";
import { useWorkspace } from "../WorkspaceContext";
import { createObservation } from "../lib/workspace";
import type { Severity, Shift } from "../domain";

const initial = { title: "", equipment: "Labeler 02", area: "Packaging hall", severity: "Moderate" as Severity, owner: "Noah Williams", due: "2026-08-13T11:00", shift: "Day" as Shift, observation: "", decision: "", evidence: "" };
export default function NewIssue() {
  const { update } = useWorkspace(); const navigate = useNavigate(); const [form, setForm] = useState(initial); const [error, setError] = useState("");
  const submit = (event: React.FormEvent) => { event.preventDefault(); try { let id = ""; update((current) => { const next = createObservation(current, form); id = next.issues[0].id; return next; }); navigate(`/issues/${id}`); } catch (reason) { setError((reason as Error).message); } };
  return <div className="page record-form-page"><div className="detail-top"><Link to="/issues">← Issue register</Link><span>New observation</span></div><header><p className="eyebrow">Observation · Source record</p><h1>Record what changed before deciding what follows.</h1></header><form className="record-form" onSubmit={submit}><section><p className="eyebrow">Condition</p><label>Short condition title<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })}/></label><div className="form-pair"><label>Equipment<select value={form.equipment} onChange={(event) => setForm({ ...form, equipment: event.target.value })}>{EQUIPMENT.map((item) => <option key={item}>{item}</option>)}</select></label><label>Area<input value={form.area} onChange={(event) => setForm({ ...form, area: event.target.value })}/></label></div><div className="form-pair"><label>Severity<select value={form.severity} onChange={(event) => setForm({ ...form, severity: event.target.value as Severity })}><option>Low</option><option>Moderate</option><option>High</option><option>Critical</option></select></label><label>Shift<select value={form.shift} onChange={(event) => setForm({ ...form, shift: event.target.value as Shift })}><option>Night</option><option>Day</option><option>Evening</option></select></label></div></section><section><p className="eyebrow">Continuity context</p><label>What changed?<textarea rows={5} value={form.observation} onChange={(event) => setForm({ ...form, observation: event.target.value })}/><small>{form.observation.length} · minimum 30</small></label><label>What should happen next?<textarea rows={4} value={form.decision} onChange={(event) => setForm({ ...form, decision: event.target.value })}/><small>{form.decision.length} · minimum 20</small></label><label>Evidence already retained<textarea rows={3} value={form.evidence} onChange={(event) => setForm({ ...form, evidence: event.target.value })}/></label></section><section><p className="eyebrow">Responsibility</p><label>Owner<select value={form.owner} onChange={(event) => setForm({ ...form, owner: event.target.value })}>{PEOPLE.map((person) => <option key={person}>{person}</option>)}</select></label><label>Decision due<input type="datetime-local" value={form.due} onChange={(event) => setForm({ ...form, due: event.target.value })}/></label><p className="form-guidance">Recording an observation does not automatically carry it into another shift. A supervisor must prepare that transfer explicitly.</p>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary">Save observation</button></section></form></div>;
}
