import { useState } from "react";
import { useWorkspace } from "../WorkspaceContext";
import { filterIssues, issuesCsv } from "../lib/filters";
import { unacknowledged } from "../lib/workspace";
import type { Severity } from "../domain";

export default function Reports() {
  const { workspace } = useWorkspace(); const [severity, setSeverity] = useState<"All" | Severity>("All"); const [state, setState] = useState<"All" | "Open" | "Resolved">("Open"); const records = filterIssues(workspace.issues, { query: "", severity, state });
  const download = () => { const blob = new Blob([issuesCsv(records)], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "carryover-shift-brief-2026-08-13.csv"; anchor.click(); URL.revokeObjectURL(url); };
  const events = [...workspace.issues.flatMap((issue) => issue.audit), ...workspace.handoffs.flatMap((handoff) => handoff.audit), ...workspace.actions.flatMap((action) => action.audit)].sort((a, b) => b.at.localeCompare(a.at)).slice(0, 5);
  return <div className="page report"><header className="page-head compact"><div><p className="eyebrow">Reports · Operating brief</p><h1>Turn the record into a usable shift artifact.</h1><p>Filters affect the condition ledger; responsibility transfers and decisions remain visible for context.</p></div><div className="report-actions"><button className="primary" onClick={() => window.print()}>Print / Save PDF</button><button onClick={download}>Export CSV</button></div></header><section className="filters no-print"><label>Severity<select value={severity} onChange={(event) => setSeverity(event.target.value as typeof severity)}><option>All</option><option>Critical</option><option>High</option><option>Moderate</option><option>Low</option></select></label><label>State<select value={state} onChange={(event) => setState(event.target.value as typeof state)}><option>All</option><option>Open</option><option>Resolved</option></select></label><span>{records.length} included</span></section><section className="print-head"><strong>CARRYOVER / SHIFT BRIEF</strong><span>{workspace.plant} · Record date 13 Aug 2026 · 07:30</span><span>Filters · {severity} severity · {state} state</span></section><section className="report-summary"><div><strong>{records.length}</strong><span>included conditions</span></div><div><strong>{unacknowledged(workspace.handoffs).length}</strong><span>unacknowledged transfers</span></div><div><strong>{workspace.actions.filter((action) => action.state !== "Closed").length}</strong><span>outstanding actions</span></div></section><div className="report-grid"><section className="brief-list"><h2>Conditions requiring continuity</h2>{records.map((issue) => <article key={issue.id}><header><strong>{issue.id} · {issue.title}</strong><span>{issue.severity} · {issue.status}</span></header><p>{issue.decision}</p><small>{issue.equipment} · Owner {issue.owner} · Due {issue.due.replace("T", " ")}</small></article>)}{records.length === 0 && <p>No conditions match the active filters.</p>}</section><section className="decision-log"><h2>Latest responsibility and decisions</h2>{events.map((event) => <article key={event.id}><time>{event.at.replace("T", " · ")}</time><strong>{event.event}</strong><span>{event.actor}</span>{event.detail && <p>{event.detail}</p>}</article>)}</section></div><p className="report-disclosure">Fictional demonstration data. This report does not describe a real factory, employer, person, incident, or equipment record. Carryover does not replace approved plant procedures.</p></div>;
}
